### ISSUE TITLE
`shiny-depoy` action fails

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/HTAN-data-curator#18]
**Describe the bug**
Github action `shiny-deploy` to deploy data curator to production [failed during `Install R package dependencies step`](https://github.com/ncihtan/HTAN-data-curator/actions/runs/2625556786/attempts/1)
Last lines of output below. I think this means that the github auth token is expired.

```
trying URL 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest/src/contrib/dplyr_1.0.9.tar.gz'
Content type 'binary/octet-stream' length 1284626 bytes (1.2 MB)
==================================================
downloaded 1.2 MB
* installing *binary* package ‘dplyr’ ...
* DONE (dplyr)
The downloaded source packages are in
	‘/tmp/Rtmpk4CBqR/downloaded_packages’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *binary* package ‘tidyr’ ...
* DONE (tidyr)
> remotes::install_github(gh)
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
  Rate limit remaining: 59/60
  Rate limit reset at: 2022-07-11 12:07:54 UTC
```

**To Reproduce**
1. Go to actions tab in `ncihtan/HTAN-data-curator` repo
2. Click on the last failed run
3. Click on rerun jobs
4.Click rerun all jobs
5. Wait for job to faile
6. See error in `Install R Package Dependencies` step

**Expected behavior**

**Priority** (select one)
- [ ] ~~Minor ⬇️~~
- [ ] ~~Major 📢~~
- [x] **Critical 🆘**

**Screenshots**
Error diplayed above

**Comment by adamjtaylor** [comment]
Secrets are set in [line 27](https://github.com/ncihtan/HTAN-data-curator/blob/main/.github/workflows/shinyapps_deploy.yml#L27) of `shinyapps_deploy.yaml` as the variable `secrets.REPO_PAT`
In secrets management `REPO_PAT` was last updated on 28 Feb

**Comment by adamjtaylor** [comment]
Last successful run was on 6 June, first failed run was on 7 June, so possibly the PAT expired in this period. This is 100 days which might make sense as a round number for PAT validity

**Comment by adamjtaylor** [comment]
FYI @milen-sage  - I'm not sure what scope the github PAT needs to have - is it installing from a private repo?

**Comment by adamjtaylor** [comment]
It looks like it is just installing two packages with `remotes::install_github`

```
gh <- c(
  "dreamRs/shinypop",
  # switch back to use cran install 'shinydashboardPlus'
  # once they make a release to fix icons
  # https://github.com/RinteRface/shinydashboardPlus
  "RinteRface/shinydashboardPlus"
)
```
None of these are private, so any github PAT should work. I will try replacing the `REPO_PAT` secret with a new PAT from my own account.

**Comment by adamjtaylor** [comment]
PAT created by @adamjtaylor with no additional permissions and added as `REPO_PAT` secret.
Failed action relaunched.

**Comment by adamjtaylor** [comment]
Using the new PAT led to successful completion of the `shiny-deploy` action.

**Comment by adamjtaylor** [comment]
Closing the issue as this appears fixed.
@aclayton555 can we add to a future HTAN/FAIR data workstream meeting to check in who owns all the secrets required and how they are reset if they time out.

**Comment by aclayton555** [comment]
Thanks! I have noted this for our next HTAN/FAIR Stakeholder meeting
