### ISSUE TITLE
Project folder list stuck on 'Generating'

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/HTAN-data-curator#37]
**Describe the bug**
DCA does not list available folders... instead shows "Generating" (see screenshot below.
Also a significant >1 min delay in the synapse load screen.

**To Reproduce**
1. Go to https://sagebio.shinyapps.io/HTAN-data-curator-staging/ or https://sagebio.shinyapps.io/HTAN-data-curator/
2. Click on '>>>'
4. See that the Folder dropdown says `Generating` with no folders able to select

**Expected behavior**

A list of folders in the Synapse project are shown

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [x] Critical 🆘

**Screenshots**
![Screenshot 2022-11-07 at 17 18 34](https://user-images.githubusercontent.com/14945787/200373858-2712c5f6-ba54-4489-955b-8c6287884084.jpg)

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by adamjtaylor** [comment]
OK. Error here was me not selecting a project... When I do it does list the folders promptly. (But it would be a good UI improvement to make the text clearer.

**Comment by aclayton555** [comment]
@adamjtaylor have you already submitted a ticket through the FAIR JIra desk?

**Comment by adamjtaylor** [comment]
Issue can be closed because this was me just forgetting how to use DCA.   

🤦

Will open separate issue for next sprint to monitor DCA performance which may needs FAIR escalation but this can be closed
