### ISSUE TITLE
Template name is prefixed by a space

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/HTAN-data-curator#60]
Reported by Duke in HTAN service desk ticket [HTAN-141](https://sagebionetworks.jira.com/jira/servicedesk/projects/HTAN/queues/custom/1/HTAN-141)

To reproduce: 
- In production DCA select "HTAN Duke", "clinical_diagnosis" folder and "Diagnosis" template
- Generate template and click through to Google Sheet
- See that document name is " Diagnosis" (note space at front)

![Screenshot 2022-11-29 at 15 54 57](https://user-images.githubusercontent.com/14945787/204578937-d1552501-381d-4ee1-9191-533ba0e7d76d.jpg)

**Comment by adamjtaylor** [comment]
I think this would be categorised as `escalate`.... its probably a FAIR data task. I'm not sure what the expected behavior is. Most templates seem to have the form `HTAN <component>`

**Comment by adamjtaylor** [comment]
Discuss in Next FAIR/HTAN meeting on 12/12.
If this is expected behaviour then OK.
If not FAIR service desk ticket

**Comment by adamjtaylor** [comment]
Discussed at FAIR data stakeholder meeting.
Is not expected behaviour.
Assigned to @milen-sage to investigate and triage.

**Comment by adamjtaylor** [comment]
Discuss in Next FAIR/HTAN meeting on 01/09.
- [ ]  FAIR service desk ticket?
- [ ] Where tracked in FAIR backlog?

**Comment by adamjtaylor** [comment]
@milen-sage to link FAIR data ticket once open.

**Comment by milen-sage** [comment]
@MiekoHash could we follow up to add some details according to the bug template?

**Comment by aclayton555** [comment]
@MiekoHash or @milen-sage Are there any updates related to this issue, or is there a corresponding FAIR ticket where this is tracked?

**Comment by MiekoHash** [comment]
@aclayton555 Is this a dupe of this ticket?  cc: @milen-sage 
https://github.com/ncihtan/data-models/issues/139#issuecomment-1485792981

**Comment by aclayton555** [comment]
@MiekoHash no this is not a duplicate. #139 refers to the Filename attribute, but this issue is referring to a space in the name of the metadata template itself. 

This is not a blocker for HTAN, but we raised this with Milen and confirmed this was unexpected behaviour and somethings that should ideally be fixed, and would need to be fixed on the FAIR side. I am not aware of an existing FAIR ticket on this (if there is one, please link it here). FAIR should evaluate how much a priority this is to fix.

**Comment by MiekoHash** [comment]
Got it. I will hunt it down and will come back here with my findings. Thanks for taking the time to explain the difference and letting us know of the HTAN priority.

**Comment by MiekoHash** [comment]
Now this is tracked in JIRA: https://sagebionetworks.jira.com/browse/FDS-270

**Comment by aclayton555** [comment]
We will not see the fix for this realized until we shift to the multi-tenant DCA
