### ISSUE TITLE
Update DCA to include HTAN-163 fix

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/HTAN-data-curator#68]
[HTAN-163](https://sagebionetworks.jira.com/browse/HTAN-163) requires a fix in DCA.
This issue is to track its deployment in the HTAN DCA instance
@milen-sage to confirm when this is released in the upstream repo.

**Comment by adamjtaylor** [comment]
@milen-sage, @MiekoHash  it looks like there are some conflicts in the linked PR to update our DCA. Would you be able to assign someone to help resolve. We are keen to get this fix deployed to staging ASAP and to Production at the end of the week.

**Comment by milen-sage** [comment]
@adamjtaylor @afwillia is preparing the DCA release. @afwillia could you take a look at conflicts?
