### ISSUE TITLE
Dashboard Disconnect Uploading Imaging Level 2 Manifest

### ISSUE THREAD

**Issue by PozhidayevaDarya** [ncihtan/HTAN-data-curator#70]
**Describe the bug**
DCA Dashboard disconnects when uploading Imaging Level 2 Manifest for HTAPP. 

**To Reproduce**
1. Validate imaging level 2 manifest for HTAPP MERFISH Level 2.
2. Wait.
3. See disconnected from server error.

Shows disconnected from server during submission/validation.

Manifest File:

[_Imaging Level 2.csv](https://github.com/ncihtan/HTAN-data-curator/files/11265190/_Imaging.Level.2.csv)

**Comment by adamjtaylor** [comment]
Apologies @PozhidayevaDarya, I only just spotted this. 

Can try and debug. 
FYI @aclayton555

**Comment by adamjtaylor** [comment]
@PozhidayevaDarya is this still an issue? If so can you open an HTAN service desk ticket and link here? Apologies if there already is one that has been dropped.

**Comment by PozhidayevaDarya** [comment]
> @PozhidayevaDarya is this still an issue? If so can you open an HTAN service desk ticket and link here? Apologies if there already is one that has been dropped.

Yep still happening and did it here: https://sagebionetworks.jira.com/browse/HTAN-203

Thanks!

**Comment by adamjtaylor** [comment]
Confirmed fixed in mtDCA.
